# Site settings
title: "Errikos Melissinos' Website"
description: "PhD Candidate"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Errikos Melissinos"
resume_title:                   "<p>Welcome to my webiste! </p> <p>I am a PhD candidate at Goethe University Frankfurt and Research Assistant at Leibniz Institute for Financial Research SAFE.</p>"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "melissinos@safe-frankfurt.de"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
# display_header_contact_info:    "false"

resume_header_intro: "<p>I am interested in macroeconomics and finance, with a special focus on monetary economics, asset pricing and solution methods.</p> <p>I will be on the 2023/2024 academic job market.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
# resume_section_education:       true
resume_section_projects:        true
resume_section_projects2:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "https://twitter.com/errikMelissinos"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://safe-frankfurt.de/research/researchers/researchers-details/showauthor/1109-melissinos.html"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
# resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
